#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PersonalContacts.Resource", IsApplication=true)]

namespace PersonalContacts
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int map = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060018
			public const int contactEmail = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int contactMobile = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int contactName = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int imgHomeAddressMap = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int lblEmail = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int lblFacebookUrl = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int lblFullName = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int lblHomeAddress = 2131099650;
			
			// aapt resource value: 0x7f060013
			public const int lblHomeAddressMap = 2131099667;
			
			// aapt resource value: 0x7f060007
			public const int lblHomePhone = 2131099655;
			
			// aapt resource value: 0x7f06000f
			public const int lblLinkedInUrl = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int lblMobile = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int lblWorkPhone = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int listViewData = 2131099669;
			
			// aapt resource value: 0x7f060006
			public const int txtCountry = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int txtEmail = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int txtFacebookUrl = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int txtFullName = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int txtHomeAddress = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int txtHomePhone = 2131099656;
			
			// aapt resource value: 0x7f060010
			public const int txtLinkedInUrl = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int txtMobile = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int txtState = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int txtSuburb = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int txtWorkPhone = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Row = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
